/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportingApiSkillsRouteImport } from './routes/_reporting/api.skills'
import { Route as ReportingApiReportsRouteImport } from './routes/_reporting/api.reports'
import { Route as ReportingApiReportSseRouteImport } from './routes/_reporting/api.report-sse'
import { Route as ReportingApiReportEventRouteImport } from './routes/_reporting/api.report-event'
import { Route as ReportingApiInvalidateRouteImport } from './routes/_reporting/api.invalidate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingApiSkillsRoute = ReportingApiSkillsRouteImport.update({
  id: '/_reporting/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingApiReportsRoute = ReportingApiReportsRouteImport.update({
  id: '/_reporting/api/reports',
  path: '/api/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingApiReportSseRoute = ReportingApiReportSseRouteImport.update({
  id: '/_reporting/api/report-sse',
  path: '/api/report-sse',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingApiReportEventRoute = ReportingApiReportEventRouteImport.update({
  id: '/_reporting/api/report-event',
  path: '/api/report-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingApiInvalidateRoute = ReportingApiInvalidateRouteImport.update({
  id: '/_reporting/api/invalidate',
  path: '/api/invalidate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/invalidate': typeof ReportingApiInvalidateRoute
  '/api/report-event': typeof ReportingApiReportEventRoute
  '/api/report-sse': typeof ReportingApiReportSseRoute
  '/api/reports': typeof ReportingApiReportsRoute
  '/api/skills': typeof ReportingApiSkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/invalidate': typeof ReportingApiInvalidateRoute
  '/api/report-event': typeof ReportingApiReportEventRoute
  '/api/report-sse': typeof ReportingApiReportSseRoute
  '/api/reports': typeof ReportingApiReportsRoute
  '/api/skills': typeof ReportingApiSkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_reporting/api/invalidate': typeof ReportingApiInvalidateRoute
  '/_reporting/api/report-event': typeof ReportingApiReportEventRoute
  '/_reporting/api/report-sse': typeof ReportingApiReportSseRoute
  '/_reporting/api/reports': typeof ReportingApiReportsRoute
  '/_reporting/api/skills': typeof ReportingApiSkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/invalidate'
    | '/api/report-event'
    | '/api/report-sse'
    | '/api/reports'
    | '/api/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/invalidate'
    | '/api/report-event'
    | '/api/report-sse'
    | '/api/reports'
    | '/api/skills'
  id:
    | '__root__'
    | '/'
    | '/_reporting/api/invalidate'
    | '/_reporting/api/report-event'
    | '/_reporting/api/report-sse'
    | '/_reporting/api/reports'
    | '/_reporting/api/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportingApiInvalidateRoute: typeof ReportingApiInvalidateRoute
  ReportingApiReportEventRoute: typeof ReportingApiReportEventRoute
  ReportingApiReportSseRoute: typeof ReportingApiReportSseRoute
  ReportingApiReportsRoute: typeof ReportingApiReportsRoute
  ReportingApiSkillsRoute: typeof ReportingApiSkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_reporting/api/skills': {
      id: '/_reporting/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ReportingApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_reporting/api/reports': {
      id: '/_reporting/api/reports'
      path: '/api/reports'
      fullPath: '/api/reports'
      preLoaderRoute: typeof ReportingApiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_reporting/api/report-sse': {
      id: '/_reporting/api/report-sse'
      path: '/api/report-sse'
      fullPath: '/api/report-sse'
      preLoaderRoute: typeof ReportingApiReportSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_reporting/api/report-event': {
      id: '/_reporting/api/report-event'
      path: '/api/report-event'
      fullPath: '/api/report-event'
      preLoaderRoute: typeof ReportingApiReportEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_reporting/api/invalidate': {
      id: '/_reporting/api/invalidate'
      path: '/api/invalidate'
      fullPath: '/api/invalidate'
      preLoaderRoute: typeof ReportingApiInvalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportingApiInvalidateRoute: ReportingApiInvalidateRoute,
  ReportingApiReportEventRoute: ReportingApiReportEventRoute,
  ReportingApiReportSseRoute: ReportingApiReportSseRoute,
  ReportingApiReportsRoute: ReportingApiReportsRoute,
  ReportingApiSkillsRoute: ReportingApiSkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
